/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ArithmeticInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "add"
      | "confidentialProtocolId"
      | "initialize"
      | "isInitialized"
      | "multiply"
      | "subtract"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AdditionPerformed"
      | "MultiplicationPerformed"
      | "SubtractionPerformed"
      | "ValuesInitialized"
  ): EventFragment;

  encodeFunctionData(functionFragment: "add", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isInitialized",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "multiply", values?: undefined): string;
  encodeFunctionData(functionFragment: "subtract", values?: undefined): string;

  decodeFunctionResult(functionFragment: "add", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isInitialized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "multiply", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "subtract", data: BytesLike): Result;
}

export namespace AdditionPerformedEvent {
  export type InputTuple = [result: BytesLike];
  export type OutputTuple = [result: string];
  export interface OutputObject {
    result: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MultiplicationPerformedEvent {
  export type InputTuple = [result: BytesLike];
  export type OutputTuple = [result: string];
  export interface OutputObject {
    result: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubtractionPerformedEvent {
  export type InputTuple = [result: BytesLike];
  export type OutputTuple = [result: string];
  export interface OutputObject {
    result: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ValuesInitializedEvent {
  export type InputTuple = [initializer: AddressLike];
  export type OutputTuple = [initializer: string];
  export interface OutputObject {
    initializer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Arithmetic extends BaseContract {
  connect(runner?: ContractRunner | null): Arithmetic;
  waitForDeployment(): Promise<this>;

  interface: ArithmeticInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  add: TypedContractMethod<[], [string], "nonpayable">;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  initialize: TypedContractMethod<
    [
      encryptedValue1: BytesLike,
      encryptedValue2: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  isInitialized: TypedContractMethod<[], [boolean], "view">;

  multiply: TypedContractMethod<[], [string], "nonpayable">;

  subtract: TypedContractMethod<[], [string], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "add"
  ): TypedContractMethod<[], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [
      encryptedValue1: BytesLike,
      encryptedValue2: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isInitialized"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "multiply"
  ): TypedContractMethod<[], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "subtract"
  ): TypedContractMethod<[], [string], "nonpayable">;

  getEvent(
    key: "AdditionPerformed"
  ): TypedContractEvent<
    AdditionPerformedEvent.InputTuple,
    AdditionPerformedEvent.OutputTuple,
    AdditionPerformedEvent.OutputObject
  >;
  getEvent(
    key: "MultiplicationPerformed"
  ): TypedContractEvent<
    MultiplicationPerformedEvent.InputTuple,
    MultiplicationPerformedEvent.OutputTuple,
    MultiplicationPerformedEvent.OutputObject
  >;
  getEvent(
    key: "SubtractionPerformed"
  ): TypedContractEvent<
    SubtractionPerformedEvent.InputTuple,
    SubtractionPerformedEvent.OutputTuple,
    SubtractionPerformedEvent.OutputObject
  >;
  getEvent(
    key: "ValuesInitialized"
  ): TypedContractEvent<
    ValuesInitializedEvent.InputTuple,
    ValuesInitializedEvent.OutputTuple,
    ValuesInitializedEvent.OutputObject
  >;

  filters: {
    "AdditionPerformed(bytes32)": TypedContractEvent<
      AdditionPerformedEvent.InputTuple,
      AdditionPerformedEvent.OutputTuple,
      AdditionPerformedEvent.OutputObject
    >;
    AdditionPerformed: TypedContractEvent<
      AdditionPerformedEvent.InputTuple,
      AdditionPerformedEvent.OutputTuple,
      AdditionPerformedEvent.OutputObject
    >;

    "MultiplicationPerformed(bytes32)": TypedContractEvent<
      MultiplicationPerformedEvent.InputTuple,
      MultiplicationPerformedEvent.OutputTuple,
      MultiplicationPerformedEvent.OutputObject
    >;
    MultiplicationPerformed: TypedContractEvent<
      MultiplicationPerformedEvent.InputTuple,
      MultiplicationPerformedEvent.OutputTuple,
      MultiplicationPerformedEvent.OutputObject
    >;

    "SubtractionPerformed(bytes32)": TypedContractEvent<
      SubtractionPerformedEvent.InputTuple,
      SubtractionPerformedEvent.OutputTuple,
      SubtractionPerformedEvent.OutputObject
    >;
    SubtractionPerformed: TypedContractEvent<
      SubtractionPerformedEvent.InputTuple,
      SubtractionPerformedEvent.OutputTuple,
      SubtractionPerformedEvent.OutputObject
    >;

    "ValuesInitialized(address)": TypedContractEvent<
      ValuesInitializedEvent.InputTuple,
      ValuesInitializedEvent.OutputTuple,
      ValuesInitializedEvent.OutputObject
    >;
    ValuesInitialized: TypedContractEvent<
      ValuesInitializedEvent.InputTuple,
      ValuesInitializedEvent.OutputTuple,
      ValuesInitializedEvent.OutputObject
    >;
  };
}
