/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface EntropyArithmeticInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "add"
      | "addWithEntropy"
      | "confidentialProtocolId"
      | "entropyOracle"
      | "entropyRequests"
      | "getEntropyOracle"
      | "initialize"
      | "isInitialized"
      | "multiply"
      | "multiplyWithEntropy"
      | "requestEntropy"
      | "subtract"
      | "subtractWithEntropy"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AdditionPerformed"
      | "EntropyAdditionPerformed"
      | "EntropyMultiplicationPerformed"
      | "EntropyRequested"
      | "EntropySubtractionPerformed"
      | "MultiplicationPerformed"
      | "SubtractionPerformed"
      | "ValuesInitialized"
  ): EventFragment;

  encodeFunctionData(functionFragment: "add", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "addWithEntropy",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "entropyOracle",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "entropyRequests",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEntropyOracle",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [BytesLike, BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isInitialized",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "multiply", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "multiplyWithEntropy",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "requestEntropy",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "subtract", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "subtractWithEntropy",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "add", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "addWithEntropy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "entropyOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "entropyRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEntropyOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isInitialized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "multiply", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "multiplyWithEntropy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestEntropy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "subtract", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "subtractWithEntropy",
    data: BytesLike
  ): Result;
}

export namespace AdditionPerformedEvent {
  export type InputTuple = [result: BytesLike];
  export type OutputTuple = [result: string];
  export interface OutputObject {
    result: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EntropyAdditionPerformedEvent {
  export type InputTuple = [requestId: BigNumberish, result: BytesLike];
  export type OutputTuple = [requestId: bigint, result: string];
  export interface OutputObject {
    requestId: bigint;
    result: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EntropyMultiplicationPerformedEvent {
  export type InputTuple = [requestId: BigNumberish, result: BytesLike];
  export type OutputTuple = [requestId: bigint, result: string];
  export interface OutputObject {
    requestId: bigint;
    result: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EntropyRequestedEvent {
  export type InputTuple = [requestId: BigNumberish, caller: AddressLike];
  export type OutputTuple = [requestId: bigint, caller: string];
  export interface OutputObject {
    requestId: bigint;
    caller: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EntropySubtractionPerformedEvent {
  export type InputTuple = [requestId: BigNumberish, result: BytesLike];
  export type OutputTuple = [requestId: bigint, result: string];
  export interface OutputObject {
    requestId: bigint;
    result: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MultiplicationPerformedEvent {
  export type InputTuple = [result: BytesLike];
  export type OutputTuple = [result: string];
  export interface OutputObject {
    result: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubtractionPerformedEvent {
  export type InputTuple = [result: BytesLike];
  export type OutputTuple = [result: string];
  export interface OutputObject {
    result: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ValuesInitializedEvent {
  export type InputTuple = [initializer: AddressLike];
  export type OutputTuple = [initializer: string];
  export interface OutputObject {
    initializer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EntropyArithmetic extends BaseContract {
  connect(runner?: ContractRunner | null): EntropyArithmetic;
  waitForDeployment(): Promise<this>;

  interface: EntropyArithmeticInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  add: TypedContractMethod<[], [string], "nonpayable">;

  addWithEntropy: TypedContractMethod<
    [requestId: BigNumberish],
    [string],
    "nonpayable"
  >;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  entropyOracle: TypedContractMethod<[], [string], "view">;

  entropyRequests: TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;

  getEntropyOracle: TypedContractMethod<[], [string], "view">;

  initialize: TypedContractMethod<
    [
      encryptedValue1: BytesLike,
      encryptedValue2: BytesLike,
      inputProof1: BytesLike,
      inputProof2: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  isInitialized: TypedContractMethod<[], [boolean], "view">;

  multiply: TypedContractMethod<[], [string], "nonpayable">;

  multiplyWithEntropy: TypedContractMethod<
    [requestId: BigNumberish],
    [string],
    "nonpayable"
  >;

  requestEntropy: TypedContractMethod<[tag: BytesLike], [bigint], "payable">;

  subtract: TypedContractMethod<[], [string], "nonpayable">;

  subtractWithEntropy: TypedContractMethod<
    [requestId: BigNumberish],
    [string],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "add"
  ): TypedContractMethod<[], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "addWithEntropy"
  ): TypedContractMethod<[requestId: BigNumberish], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "entropyOracle"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "entropyRequests"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "getEntropyOracle"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [
      encryptedValue1: BytesLike,
      encryptedValue2: BytesLike,
      inputProof1: BytesLike,
      inputProof2: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isInitialized"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "multiply"
  ): TypedContractMethod<[], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "multiplyWithEntropy"
  ): TypedContractMethod<[requestId: BigNumberish], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "requestEntropy"
  ): TypedContractMethod<[tag: BytesLike], [bigint], "payable">;
  getFunction(
    nameOrSignature: "subtract"
  ): TypedContractMethod<[], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "subtractWithEntropy"
  ): TypedContractMethod<[requestId: BigNumberish], [string], "nonpayable">;

  getEvent(
    key: "AdditionPerformed"
  ): TypedContractEvent<
    AdditionPerformedEvent.InputTuple,
    AdditionPerformedEvent.OutputTuple,
    AdditionPerformedEvent.OutputObject
  >;
  getEvent(
    key: "EntropyAdditionPerformed"
  ): TypedContractEvent<
    EntropyAdditionPerformedEvent.InputTuple,
    EntropyAdditionPerformedEvent.OutputTuple,
    EntropyAdditionPerformedEvent.OutputObject
  >;
  getEvent(
    key: "EntropyMultiplicationPerformed"
  ): TypedContractEvent<
    EntropyMultiplicationPerformedEvent.InputTuple,
    EntropyMultiplicationPerformedEvent.OutputTuple,
    EntropyMultiplicationPerformedEvent.OutputObject
  >;
  getEvent(
    key: "EntropyRequested"
  ): TypedContractEvent<
    EntropyRequestedEvent.InputTuple,
    EntropyRequestedEvent.OutputTuple,
    EntropyRequestedEvent.OutputObject
  >;
  getEvent(
    key: "EntropySubtractionPerformed"
  ): TypedContractEvent<
    EntropySubtractionPerformedEvent.InputTuple,
    EntropySubtractionPerformedEvent.OutputTuple,
    EntropySubtractionPerformedEvent.OutputObject
  >;
  getEvent(
    key: "MultiplicationPerformed"
  ): TypedContractEvent<
    MultiplicationPerformedEvent.InputTuple,
    MultiplicationPerformedEvent.OutputTuple,
    MultiplicationPerformedEvent.OutputObject
  >;
  getEvent(
    key: "SubtractionPerformed"
  ): TypedContractEvent<
    SubtractionPerformedEvent.InputTuple,
    SubtractionPerformedEvent.OutputTuple,
    SubtractionPerformedEvent.OutputObject
  >;
  getEvent(
    key: "ValuesInitialized"
  ): TypedContractEvent<
    ValuesInitializedEvent.InputTuple,
    ValuesInitializedEvent.OutputTuple,
    ValuesInitializedEvent.OutputObject
  >;

  filters: {
    "AdditionPerformed(bytes32)": TypedContractEvent<
      AdditionPerformedEvent.InputTuple,
      AdditionPerformedEvent.OutputTuple,
      AdditionPerformedEvent.OutputObject
    >;
    AdditionPerformed: TypedContractEvent<
      AdditionPerformedEvent.InputTuple,
      AdditionPerformedEvent.OutputTuple,
      AdditionPerformedEvent.OutputObject
    >;

    "EntropyAdditionPerformed(uint256,bytes32)": TypedContractEvent<
      EntropyAdditionPerformedEvent.InputTuple,
      EntropyAdditionPerformedEvent.OutputTuple,
      EntropyAdditionPerformedEvent.OutputObject
    >;
    EntropyAdditionPerformed: TypedContractEvent<
      EntropyAdditionPerformedEvent.InputTuple,
      EntropyAdditionPerformedEvent.OutputTuple,
      EntropyAdditionPerformedEvent.OutputObject
    >;

    "EntropyMultiplicationPerformed(uint256,bytes32)": TypedContractEvent<
      EntropyMultiplicationPerformedEvent.InputTuple,
      EntropyMultiplicationPerformedEvent.OutputTuple,
      EntropyMultiplicationPerformedEvent.OutputObject
    >;
    EntropyMultiplicationPerformed: TypedContractEvent<
      EntropyMultiplicationPerformedEvent.InputTuple,
      EntropyMultiplicationPerformedEvent.OutputTuple,
      EntropyMultiplicationPerformedEvent.OutputObject
    >;

    "EntropyRequested(uint256,address)": TypedContractEvent<
      EntropyRequestedEvent.InputTuple,
      EntropyRequestedEvent.OutputTuple,
      EntropyRequestedEvent.OutputObject
    >;
    EntropyRequested: TypedContractEvent<
      EntropyRequestedEvent.InputTuple,
      EntropyRequestedEvent.OutputTuple,
      EntropyRequestedEvent.OutputObject
    >;

    "EntropySubtractionPerformed(uint256,bytes32)": TypedContractEvent<
      EntropySubtractionPerformedEvent.InputTuple,
      EntropySubtractionPerformedEvent.OutputTuple,
      EntropySubtractionPerformedEvent.OutputObject
    >;
    EntropySubtractionPerformed: TypedContractEvent<
      EntropySubtractionPerformedEvent.InputTuple,
      EntropySubtractionPerformedEvent.OutputTuple,
      EntropySubtractionPerformedEvent.OutputObject
    >;

    "MultiplicationPerformed(bytes32)": TypedContractEvent<
      MultiplicationPerformedEvent.InputTuple,
      MultiplicationPerformedEvent.OutputTuple,
      MultiplicationPerformedEvent.OutputObject
    >;
    MultiplicationPerformed: TypedContractEvent<
      MultiplicationPerformedEvent.InputTuple,
      MultiplicationPerformedEvent.OutputTuple,
      MultiplicationPerformedEvent.OutputObject
    >;

    "SubtractionPerformed(bytes32)": TypedContractEvent<
      SubtractionPerformedEvent.InputTuple,
      SubtractionPerformedEvent.OutputTuple,
      SubtractionPerformedEvent.OutputObject
    >;
    SubtractionPerformed: TypedContractEvent<
      SubtractionPerformedEvent.InputTuple,
      SubtractionPerformedEvent.OutputTuple,
      SubtractionPerformedEvent.OutputObject
    >;

    "ValuesInitialized(address)": TypedContractEvent<
      ValuesInitializedEvent.InputTuple,
      ValuesInitializedEvent.OutputTuple,
      ValuesInitializedEvent.OutputObject
    >;
    ValuesInitialized: TypedContractEvent<
      ValuesInitializedEvent.InputTuple,
      ValuesInitializedEvent.OutputTuple,
      ValuesInitializedEvent.OutputObject
    >;
  };
}
